[package]
name = "name-tokenizer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []
test-bpf = []
devnet = []


[dependencies]
solana-program = "1.10.34"
num_enum = "0.5.4"
borsh = "0.9.3"
thiserror = "1.0.24"
num-traits = "0.2"
num-derive = "0.3"
enumflags2 = "0.7.1"
spl-token = {version="3.2.0", features= ["no-entrypoint"]}
bonfida-utils = "0.2.3"
spl-associated-token-account = {version = "1.0.3", features = ["no-entrypoint"]}
spl-name-service = {git = "https://github.com/solana-labs/solana-program-library", features = ["no-entrypoint"]}
mpl-token-metadata = {git = "https://github.com/metaplex-foundation/metaplex-program-library", features = ["no-entrypoint"]}


[dev-dependencies]
hexdump = "0.1.0"
solana-sdk = "1.10.34"
rand = "0.8.4"
arrayref = "0.3.6"
solana-program-test = "1.10.34"
tokio = {version="1.6", features = ["macros"]}



[lib]
crate-type = ["cdylib", "lib"]
